name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    name: ci
    uses: betabitplus/ternforge-infra-ci/.github/workflows/python-library.yml@f47ec5020e61790a5d5266e5c770380c4f2f51d2 # v5.8.0
    with:
      python-version: "3.13"
      runtime-audit-exclude-package: "py-lib-runtime"
      runtime-audit-ignore-vulnerabilities: "CVE-2025-69872"
      playwright-browsers: "chromium"
    secrets:
      app-private-key: ${{ secrets.TERNFORGE_SOURCE_READ_PRIVATE_KEY }}
